import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF8F0',
  },
  scrollViewContent: {
    paddingHorizontal: 30,
    paddingTop: 60,
    alignItems: 'center',
    paddingBottom: 40,
  },
  backButton: {
    position: 'absolute',
    top: 60,
    left: 20,
    zIndex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 30,
    color: '#333',
  },
  inputUnderlineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#ccc',
    marginBottom: 20,
    paddingVertical: 6,
    width: '100%',
  },
  icon: {
    marginRight: 10,
  },
  inputUnderline: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    minHeight: 40,
    paddingVertical: 0,
  },
  descriptionInput: {
    height: 100,
    textAlignVertical: 'top',
  },
  dateTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    width: '100%',
  },
  dateRangeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    width: '100%',
    flexWrap: 'wrap',
  },
  dateTimeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFEBCC',
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 15,
    flex: 1,
    marginHorizontal: 5,
    justifyContent: 'center',
    minWidth: '45%',
    marginBottom: 10,
  },
  dateTimeText: {
    marginLeft: 10,
    fontSize: 16,
    color: '#333',
    fontWeight: 'bold',
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '500',
    color: '#555',
    marginBottom: 10,
    marginTop: 15,
    width: '100%',
    textAlign: 'left',
  },
  categoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 20,
    justifyContent: 'flex-start',
    width: '100%',
  },
  categoryButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    backgroundColor: '#FFEBCC',
    margin: 5,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  selectedCategoryButton: {
    backgroundColor: '#FF9933',
    borderColor: '#FF9933',
  },
  disabledCategoryButton: {
    backgroundColor: '#f0f0f0',
    borderColor: '#e0e0e0',
  },
  categoryButtonText: {
    color: '#333',
    fontSize: 14,
    fontWeight: '500',
  },
  disabledCategoryButtonText: {
    color: '#aaa',
  },
  createButton: {
    backgroundColor: '#FF9933',
    paddingVertical: 15,
    borderRadius: 20,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 40,
    width: '100%',
  },
  createButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  map: {
    width: Dimensions.get('window').width * 0.9,
    height: 250,
    borderRadius: 15,
    marginBottom: 15,
    borderColor: '#FF9933',
    borderWidth: 1,
    overflow: 'hidden',
  },
  selectedCoordinatesText: {
    marginVertical: 10,
    fontSize: 15,
    color: '#666',
    fontWeight: '500',
    textAlign: 'center',
  },
});

export default styles;